# Generated by Django 3.0.6 on 2023-06-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='col',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='row',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
    ]
